import turtle
t = turtle.Turtle()
ts=t.getscreen()


def draw_smiley(offset):
    t.penup()
    t.pencolor('HotPink')
    t.fillcolor('firebrick1')
    t.goto(-100,100)
    t.pendown()
    t.pensize(9)
    t.begin_fill()
    t.goto(100,100)
    t.goto(100,-100)
    t.goto(-100,-100)
    t.goto(-100,100)
    t.end_fill()
    t.penup()
    t.goto(0,30)
    t.pendown()
    t.setheading(90)
    t.pencolor('black')
    t.fillcolor('GhostWhite')
    t.begin_fill()
    t.circle(25)
    t.circle(-25)
    t.end_fill()
    t.penup()
    t.goto(-30+offset, 30)
    t.dot(20)
    t.goto(15+offset, 30)
    t.dot(20)
    t.goto(35, -20)
    t.pencolor('dark red')
    t.pensize(8)
    t.pendown()
    t.setheading(-90)
    t.begin_fill()
    t.circle(-35, 180)
    t.goto(35, -20)
    t.end_fill()

draw_smiley(0)


ts.update()


turtle.mainloop()